name: 'Build'

on:
  workflow_dispatch:
    inputs:
      obs_version:
        description: OBS Version
        required: true
      idesk_version:
        description: iDesk Version
        required: true

env:
  CACHE_REVISION: '006'
  CEF_BUILD_VERSION_LINUX: '5060'
  CEF_BUILD_VERSION_WIN: '5060'
  QT_VERSION_MAC: '6.4.3'
  QT_VERSION_WIN: '6.4.3'
  DEPS_VERSION_WIN: '2023-06-01'
  VLC_VERSION_WIN: '3.0.0-git'
  TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
  TWITCH_HASH: ${{ secrets.TWITCH_HASH }}
  RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENTID }}
  RESTREAM_HASH: ${{ secrets.RESTREAM_HASH }}
  YOUTUBE_CLIENTID: ${{ secrets.YOUTUBE_CLIENTID }}
  YOUTUBE_CLIENTID_HASH: ${{ secrets.YOUTUBE_CLIENTID_HASH }}
  YOUTUBE_SECRET: ${{ secrets.YOUTUBE_SECRET }}
  YOUTUBE_SECRET_HASH: ${{ secrets.YOUTUBE_SECRET_HASH }}
  GPU_PRIORITY_VAL: ${{ secrets.GPU_PRIORITY_VAL }}
  OBS_VERSION_OVERRIDE: ${{ github.event.inputs.idesk_version }}
  OBS_VERSION: ${{ github.event.inputs.obs_version }}

jobs:
  build:
    name: 'Build'
    runs-on: windows-2022
    env:
      CMAKE_GENERATOR: 'Visual Studio 17 2022'
      CMAKE_SYSTEM_VERSION: '10.0.18363.657'
      VIRTUALCAM-GUID: 'A3FCE0F5-3493-419F-958A-ABA1250EC20B'
      BUILD_FOR_DISTRIBUTION: ${{ startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' }}
    defaults:
      run:
        working-directory: 'obs-studio'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: 'obs-studio'
          fetch-depth: 0

      - name: 'Add msbuild to PATH'
        uses: microsoft/setup-msbuild@v1.1

      - name: 'Edit settings of plugins'
        shell: bash
        run: |
          CONFIG="plugins/obs-websocket/src/Config.cpp"
          sed -i 's|ServerEnabled(false)|ServerEnabled(true)|' $CONFIG
          sed -i 's|AuthRequired(true)|AuthRequired(false)|'   $CONFIG
          sed -i 's|AlertsEnabled(false)|AlertsEnabled(true)|' $CONFIG

      - name: 'Install dependencies'
        run: CI/windows/01_install_dependencies.ps1 -BuildArch x64

      - name: 'Build and package OBS'
        run: |
          CI/windows/03_package_obs.ps1 -BuildArch x64 -BuildConfiguration MinSizeRel -Package
          $FILENAME = Get-ChildItem -filter "records.zip" -File
          Write-Output "FILENAME=${FILENAME}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create a release with zips in current repo
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.OBS_VERSION }}
          tag_name: ${{ env.OBS_VERSION }}
          body: 'for iDesk Studio ${{ env.OBS_VERSION_OVERRIDE }}'
          files: ${{ env.FILENAME }}